import { FlatCompat } from '@eslint/eslintrc';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import rootConfig from '../../eslint.config.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({ baseDirectory: __dirname });

export default [
  ...rootConfig,
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // next-env.d.ts is auto-regenerated by `next build`/`next dev` and its
    // triple-slash reference to .next/types is Next.js's own required
    // convention, not something to fix — never lint it.
    ignores: ['.next/**', 'next-env.d.ts'],
  },
];
